### ISSUE TITLE
Update hflip and vflip with mutable signatures 

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia-rs#103]
After this refactor https://github.com/kornia/kornia-rs/pull/102 `hflip a and `vflip` were pending to be completed

**Comment by emilmgeorge** [comment]
Hi, 

I'm interested in taking this up. 

As I understand from the linked PR, we have to use a mutable `dst` parameter for the output instead of returning, and also adjust the loop slightly for that. Please let me know if there is anything else I should consider. I have started with hflip function and hope to have something for your review soon.

**Comment by edgarriba** [comment]
@emilmgeorge yes, that's it. Beware that this morning i merged the last of series of PR to ndarray as dep. See: https://github.com/kornia/kornia-rs/pull/116

you might have to rebase

**Comment by emilmgeorge** [comment]
Thanks, yes I saw it just after I posted my prev comment. I have since rebased and updated my changes. Will PR now.

**Comment by edgarriba** [comment]
merged in #117
